package com.sdata.ecommerce.site.mapper;

import com.sdata.ecommerce.site.domain.Product;
import com.sdata.ecommerce.site.domain.ProductExample;
import com.sdata.ecommerce.site.mapper.extended.ProductMapperExtended;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ProductMapper extends ProductMapperExtended {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    List<Product> selectByExampleWithBLOBs(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    Product selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    int updateByPrimaryKey(Product record);
}