package com.sdata.ecommerce.site.domain;

import com.sdata.ecommerce.site.domain.extended.ProductExtended;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;

@Entity
@Table(name="sdata_product")
public class Product extends ProductExtended {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.id
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Id
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.name
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.keyword
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.category_id
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.manufacturer
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.msrp
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private BigDecimal msrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.saleprice
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private BigDecimal saleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.active_begin_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String activeBeginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.active_end_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String activeEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.template
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.create_by
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.create_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.update_by
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.update_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.active
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private Byte active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.description
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Column
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.id
     *
     * @return the value of sdata_product.id
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.id
     *
     * @param id the value for sdata_product.id
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.name
     *
     * @return the value of sdata_product.name
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.name
     *
     * @param name the value for sdata_product.name
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.keyword
     *
     * @return the value of sdata_product.keyword
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.keyword
     *
     * @param keyword the value for sdata_product.keyword
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.category_id
     *
     * @return the value of sdata_product.category_id
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.category_id
     *
     * @param categoryId the value for sdata_product.category_id
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.manufacturer
     *
     * @return the value of sdata_product.manufacturer
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.manufacturer
     *
     * @param manufacturer the value for sdata_product.manufacturer
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.msrp
     *
     * @return the value of sdata_product.msrp
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public BigDecimal getMsrp() {
        return msrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.msrp
     *
     * @param msrp the value for sdata_product.msrp
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setMsrp(BigDecimal msrp) {
        this.msrp = msrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.saleprice
     *
     * @return the value of sdata_product.saleprice
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public BigDecimal getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.saleprice
     *
     * @param saleprice the value for sdata_product.saleprice
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setSaleprice(BigDecimal saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.active_begin_date
     *
     * @return the value of sdata_product.active_begin_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getActiveBeginDate() {
        return activeBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.active_begin_date
     *
     * @param activeBeginDate the value for sdata_product.active_begin_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setActiveBeginDate(String activeBeginDate) {
        this.activeBeginDate = activeBeginDate == null ? null : activeBeginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.active_end_date
     *
     * @return the value of sdata_product.active_end_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getActiveEndDate() {
        return activeEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.active_end_date
     *
     * @param activeEndDate the value for sdata_product.active_end_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setActiveEndDate(String activeEndDate) {
        this.activeEndDate = activeEndDate == null ? null : activeEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.template
     *
     * @return the value of sdata_product.template
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.template
     *
     * @param template the value for sdata_product.template
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.create_by
     *
     * @return the value of sdata_product.create_by
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.create_by
     *
     * @param createBy the value for sdata_product.create_by
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.create_date
     *
     * @return the value of sdata_product.create_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.create_date
     *
     * @param createDate the value for sdata_product.create_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.update_by
     *
     * @return the value of sdata_product.update_by
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.update_by
     *
     * @param updateBy the value for sdata_product.update_by
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.update_date
     *
     * @return the value of sdata_product.update_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.update_date
     *
     * @param updateDate the value for sdata_product.update_date
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.active
     *
     * @return the value of sdata_product.active
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public Byte getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.active
     *
     * @param active the value for sdata_product.active
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setActive(Byte active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.description
     *
     * @return the value of sdata_product.description
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.description
     *
     * @param description the value for sdata_product.description
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Product other = (Product) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getKeyword() == null ? other.getKeyword() == null : this.getKeyword().equals(other.getKeyword()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getManufacturer() == null ? other.getManufacturer() == null : this.getManufacturer().equals(other.getManufacturer()))
            && (this.getMsrp() == null ? other.getMsrp() == null : this.getMsrp().equals(other.getMsrp()))
            && (this.getSaleprice() == null ? other.getSaleprice() == null : this.getSaleprice().equals(other.getSaleprice()))
            && (this.getActiveBeginDate() == null ? other.getActiveBeginDate() == null : this.getActiveBeginDate().equals(other.getActiveBeginDate()))
            && (this.getActiveEndDate() == null ? other.getActiveEndDate() == null : this.getActiveEndDate().equals(other.getActiveEndDate()))
            && (this.getTemplate() == null ? other.getTemplate() == null : this.getTemplate().equals(other.getTemplate()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Tue Feb 26 10:23:20 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getKeyword() == null) ? 0 : getKeyword().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getManufacturer() == null) ? 0 : getManufacturer().hashCode());
        result = prime * result + ((getMsrp() == null) ? 0 : getMsrp().hashCode());
        result = prime * result + ((getSaleprice() == null) ? 0 : getSaleprice().hashCode());
        result = prime * result + ((getActiveBeginDate() == null) ? 0 : getActiveBeginDate().hashCode());
        result = prime * result + ((getActiveEndDate() == null) ? 0 : getActiveEndDate().hashCode());
        result = prime * result + ((getTemplate() == null) ? 0 : getTemplate().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}